/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_UrbanEngine_main_RendererWrapper */

#ifndef _Included_com_UrbanEngine_main_RendererWrapper
#define _Included_com_UrbanEngine_main_RendererWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_UrbanEngine_main_RendererWrapper
 * Method:    AndroidLogicCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_RendererWrapper_AndroidLogicCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_UrbanEngine_main_RendererWrapper
 * Method:    AndroidLogicUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_RendererWrapper_AndroidLogicUpdate
  (JNIEnv *, jobject);

/*
 * Class:     com_UrbanEngine_main_RendererWrapper
 * Method:    AndroidLogicDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_RendererWrapper_AndroidLogicDraw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
