/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_UrbanEngine_main_NativeLib */

#ifndef _Included_com_UrbanEngine_main_NativeLib
#define _Included_com_UrbanEngine_main_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidLogicCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidLogicCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidLogicUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidLogicUpdate
  (JNIEnv *, jclass);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidGraphicInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidGraphicInit
  (JNIEnv *, jclass);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidGraphicRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidGraphicRender
  (JNIEnv *, jclass);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidGraphicSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidGraphicSetSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    on_touch_press
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_on_1touch_1press
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
