/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_UrbanEngine_main_NativeLib */

#ifndef _Included_com_UrbanEngine_main_NativeLib
#define _Included_com_UrbanEngine_main_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidLogicCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidLogicCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidLogicUpdate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidLogicUpdate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    on_touch_press
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_on_1touch_1press
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_UrbanEngine_main_NativeLib
 * Method:    AndroidLogicDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_UrbanEngine_main_NativeLib_AndroidLogicDraw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
