Target = App

include ../makefilePatterns/${platform}.mk

MathDir = ../Math/
IOSystemDir = ../IOSystem/
WindowsDir = ../IOSystem/Windows/
AndroidDir = ../IOSystem/Android/
OpenGlDib = ../OpenGL37/
GameDib = ../Game/
PhysicLib = ../Physic/
GraphicsEngineDir = ../GraphicsEngine/
LogicDir = ../Logic/

IFlags = -I ${PhysicLib}
IFlags += -I ${GameDib}
IFlags += -I ${MathDir}
IFlags += -I ${IOSystemDir}
IFlags += -I ${AndroidDir}
IFlags += -I ${WindowsDir}
IFlags += -I ${GraphicsEngineDir}
IFlags += -I ${LogicDir}

include ../makefilePatterns/pattern.mk