set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/lib")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/lib")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY	"${CMAKE_SOURCE_DIR}/build/${PROJECT_NAME}" CACHE PATH "Directory for runtime output" FORCE)
file(MAKE_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
message(STATUS ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})